paths:
  data_root: "./data"
  db_path: "realtime_learning.db"
training:
  learning_rate: 0.0001
  buffer_size: 10000
  batch_size: 32
  update_frequency: 100
  adaptation_threshold: 0.7
model:
  embed_dim: 256
rag:
  memory_budget: 50000
pc:
  context_window: 32
workflow:
  enable_absorber: true
  enable_rl: true
  enable_evaluator: true
